### ISSUE TITLE
dcmqrscp: missing attributes in C-FIND responses

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#1123]
If there is no value available for a requested attribute, no attribute is included into the C-FIND response.
Instead an empty attribute shall be included into the C-FIND response.

**Comment by wigun** [comment]
@gunterze Doesn't this violate the DICOM Conformance, since 'Type=1C attributes' like e.g.  'The Scheduled Protocol Code Sequence contains one or more Items.' (DICOM Standard, table K.6-1, PS 3.4) are added empty with this commit, if there is no respond for this?!  I thought empty sequences like this have to be removed from the respond?!

**Comment by wigun** [comment]
@gunterze And isn't it required that unsupported query/return keys should always be removed?

**Comment by gunterze** [comment]
There are DICOM implementaions which claim on missing Type 2 attributes in C-FIND RSPs, if they were requested.
I am not aware of any DICOM implementation which claims again receive of empty Type 1C or Type 3 attributes.
