### ISSUE TITLE
Upgrade licensing to MPL-2.0

### ISSUE THREAD

**Issue by ghisvail** [dcm4che/dcm4che#209]
The current licensing terms (MPL-1.1) are [incompatible with the GPL](https://www.fsf.org/blogs/licensing/mpl-2.0-release). Besides, Mozilla explicitly marked MPL-1.1 [deprecated](https://www.mozilla.org/en-US/MPL/). Please consider upgrading the licensing terms to MPL-2.0 as a result.

**Comment by gunterze** [comment]
I would have to get the agreement of all contributers and from Agfa lawyers to change the license, which  seems unrealistic to get for the library and dcm4chee-arc-2.x. For dcm4chee-arc-light 5.x it will be possible, because there are so far only 4 contributers  - and there are no lawyers at J4Care ;)
