### ISSUE TITLE
result of jpeg-ls lossless compression is wrong

### ISSUE THREAD

**Issue by sculxp** [dcm4che/dcm4che#367]
./dcm2dcm --jlsl I80 I80.2
20:05:18,725 DEBUG - Compressor: org.dcm4che3.opencv.NativeJLSImageWriter
20:05:18,943 DEBUG - Compressed frame #1 9.153946:1 in 132 ms
I80 -> I80.2

here is original dicom file, Planar Configuration Value is 1 (1 - color-by-plane):
[I80.zip](https://github.com/dcm4che/dcm4che/files/2568375/I80.zip)
 
original dicom image looks like this:
![1](https://user-images.githubusercontent.com/12771214/48301229-6d978f80-e525-11e8-9965-578f522023c0.PNG)

after compression:
![2](https://user-images.githubusercontent.com/12771214/48301241-8d2eb800-e525-11e8-930b-b886a8558c73.PNG)

**Comment by sculxp** [comment]
doing something like this:
```
ImageIO.write(renderedImage, "png", new File("test1.png"));
ImageCV mat = ImageConversion.toMat(renderedImage, param.getSourceRegion(), false);
Imgcodecs.imwrite("test2.png", mat);
```
"test1.png" is ok
"test2.png" is wrong,

so may be  ImageConversion.toMat is not right, I'll dig deeper

**Comment by nroduit** [comment]
This image is band interleaved so it requires a conversion to pixel interleaved (this is the unique image model in opencv).

I just test with the final release 4 of opencv and it works as expected. I guess there was something wrong with the merge function. So it will be fixed in the next release.

There are other issues of transcoding because the image model in Java allows many structures which required complex conversion. Using opencv for reading the DICOM raw image in dcm4che will help because conversions will be not required anymore.

**Comment by sculxp** [comment]
Thank you very much, looking forward to  the next release.
