### ISSUE TITLE
Change DicomOutputStream.writeFileMetaInformation(fmi) to do not implicitly switch the Transfer Syntax

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#449]
Change `DicomOutputStream.writeFileMetaInformation(fmi)` to do not implicitly switch the Transfer Syntax - particularly to do **not** wrap the `OutputStream` by `DeflaterOutputStream`.

**Comment by patrick-peer** [comment]
This refactoring unfortunately breaks cases where the FMI is written separately from the dataset, and the transfer syntax is 1.2.840.10008.1.2 (Implicit VR) or 1.2.840.10008.1.2.2 (Big Endian). In these cases the corresponding booleans do not get switched anymore and, as a consequence, the DicomOutputStream encodes all followoing data elements wrongly.

I'd like to provide a fix by splitting up `DicomOutputStream.switchTransferSyntax(String)` to move the switching of `bigEndian` and `explicitVR` back to its old place and leave the setup of `DeflaterOutputStream` where it is now.
However, I am not quite sure about the implications of that, since I do not fully grasp the motivation for this issue in the first place. What do you think about the proposed fix?

**Comment by patrick-peer** [comment]
Meanwhile I proposed pull request #619
