### ISSUE TITLE
Jpg2Dcm File not found: secondaryCaptureImageMetadata.xml

### ISSUE THREAD

**Issue by yuanzzi** [dcm4che/dcm4che#488]
Hello,
When I overrode a new verison 5.17.1 class Jpg2Dcm and run it . I got a Exception: 
```
jpg2dcm: resource:secondaryCaptureImageMetadata.xml
java.io.FileNotFoundException: resource:secondaryCaptureImageMetadata.xml
	at org.dcm4che3.util.StreamUtils.openFileOrURL(StreamUtils.java:167)
```

P.S. The old version could working normally.
How to solve this problem.
Thank you

**Comment by vrindanayak** [comment]
The file (present in the `dcm4che-assembly/src/etc/ jpg2dcm` location) is not present in the classpath of `Jpg2Dcm.java` and hence this error, if you run it from an IDE. With older versions the same problem exists if you specify option `--sc`. 

With new version, the `--sc` and `--xc` options have been removed (see [issue](https://github.com/dcm4che/dcm4che/issues/474)) and instead sample metadata is always generated from these files to ensure that DICOM Type1 and Type 2 attributes are always present in the dataset, to be DICOM compliant, even if not specified/mentioned by the user.

If you run this tool from command line, this issue does not exist. If you still want to run from IDE, you may workaround by specifying the complete path of this xml file instead of `resource:secondaryCaptureImageMetadata.xml`

Please post further questions in [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che)

**Comment by yuanzzi** [comment]
Very appreciate for reply,
 I got the xml file and specifying the complete path of this xml file,
but I got the other Exception:
``` 
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.dcm4che3.imageio.codec.mpeg.MPEG2Parser.nextPacket(MPEG2Parser.java:200)
	at org.dcm4che3.imageio.codec.mpeg.MPEG2Parser.<init>(MPEG2Parser.java:95)
```
I also run jpg2dcm.bat from the command line,print this Exception too.
P.S JDK version : 1.8.0_65

Ofcause , I will Post this question in  <a href = "https://groups.google.com/forum/#!forum/dcm4che" target="_blank">dcm4che User Forum</a>
