### ISSUE TITLE
Attributes.(g|s)etDate[Range] does not consider (0008,0201) Timezone Offset From UTC for DA attributes

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#787]
Attributes.(g|s)etDate[Range] does not consider
- (0008,0201) Timezone Offset From UTC
- default Timezone specified by `Attributes.setDefaultTimeZone(TimeZone)`

for attributes with _VR_ `DA`

**Comment by JanHoracek** [comment]
Hello, 

wouldn't it cause problems when you try to get patient birth date, study date etc.?
When the images are created during summer time, but they are received by PACS few days later when it's winter time already, the date can be wrong.

Example: 
1. Patient birth date/time or study date/time is "2020-10-25 00:15:00" based on CEST, which is UTC + 2.
2. When you save it to PACS few hours later, when PACS switches to winter time (UTC + 1), getDate(...) returns "2020-10-24" because it will be converted into "2020-10-24 23:15:00"

The same happens when you receive images from different parts of the world. 

I propose that this behaviour should be parametrized and the default behaviour should be the "old" one, i.e. do not take into consideration the timezone...

BTW: There were similar issues already few years ago at DCM4CHE 3: https://dcm4che.atlassian.net/browse/LIB-420 and https://dcm4che.atlassian.net/browse/LIB-312

Kind regards

Jan

**Comment by gunterze** [comment]
The timezone is applied to the stored/accessed value, not to the time when it's stored/accessed.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by JanHoracek** [comment]
I understand that it's applied to the stored value. For example DICOM contains following attributes:

```
(0008,0201)="+0700"
(0010,0030)="20180501"
(0010,0032)="001526.000"
```

My local timezone is "+0100"

When I call 
```Date birthDate = attrs.getDate(Tag.PatientBirthDate);```
what date will I receive?

**Comment by gunterze** [comment]
Mon Apr 30 18:00:00 GMT+01:00 2018

The problem is rather caused by using Date as return type - when I start working on dcm4che-3/5, there was not yet package java.time available which provides specific types for Temporals with/without date, time and timezone information.

**Comment by hczedik** [comment]
Would actually be really nice to add methods that return the new java.time types eventually. I think it could also still be done with dcm4che3/5 in a backwards compatible way (but just providing additional methods).

**Comment by gunterze** [comment]
Ok, you convinced me. I revoke the change and just comment out the broken testDateRangeSetTimezoneOffsetFromUTC.

Seems DICOM's Timezone Offset is [rather not useable](https://groups.google.com/g/comp.protocols.dicom/c/MMca_hurWOM/m/0V-kj7e0vjYJ), as Java's legacy Date class is not fixable.
